cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel53/cfblk1','user1');
hilite_system('sampleModel53/cfblk10','user1');
hilite_system('sampleModel53/cfblk100','user1');
hilite_system('sampleModel53/cfblk101','user1');
hilite_system('sampleModel53/cfblk102','user1');
hilite_system('sampleModel53/cfblk103','user1');
hilite_system('sampleModel53/cfblk104','user1');
hilite_system('sampleModel53/cfblk11','user1');
hilite_system('sampleModel53/cfblk12','user1');
hilite_system('sampleModel53/cfblk13','user1');
hilite_system('sampleModel53/cfblk14','user1');
hilite_system('sampleModel53/cfblk15','user1');
hilite_system('sampleModel53/cfblk16','user1');
hilite_system('sampleModel53/cfblk17','user1');
hilite_system('sampleModel53/cfblk18','user1');
hilite_system('sampleModel53/cfblk19','user1');
hilite_system('sampleModel53/cfblk2','user1');
hilite_system('sampleModel53/cfblk20','user1');
hilite_system('sampleModel53/cfblk21','user1');
hilite_system('sampleModel53/cfblk22','user1');
hilite_system('sampleModel53/cfblk23','user1');
hilite_system('sampleModel53/cfblk24','user1');
hilite_system('sampleModel53/cfblk25','user1');
hilite_system('sampleModel53/cfblk26','user1');
hilite_system('sampleModel53/cfblk27','user1');
hilite_system('sampleModel53/cfblk28','user1');
hilite_system('sampleModel53/cfblk29','user1');
hilite_system('sampleModel53/cfblk3','user1');
hilite_system('sampleModel53/cfblk30','user1');
hilite_system('sampleModel53/cfblk31','user1');
hilite_system('sampleModel53/cfblk32','user1');
hilite_system('sampleModel53/cfblk33','user1');
hilite_system('sampleModel53/cfblk34','user1');
hilite_system('sampleModel53/cfblk35','user1');
hilite_system('sampleModel53/cfblk36','user1');
hilite_system('sampleModel53/cfblk37','user1');
hilite_system('sampleModel53/cfblk38','user1');
hilite_system('sampleModel53/cfblk39','user1');
hilite_system('sampleModel53/cfblk4','user1');
hilite_system('sampleModel53/cfblk40','user1');
hilite_system('sampleModel53/cfblk41','user1');
hilite_system('sampleModel53/cfblk42','user1');
hilite_system('sampleModel53/cfblk43','user1');
hilite_system('sampleModel53/cfblk44','user1');
hilite_system('sampleModel53/cfblk45','user1');
hilite_system('sampleModel53/cfblk46','user1');
hilite_system('sampleModel53/cfblk47','user1');
hilite_system('sampleModel53/cfblk48','user1');
hilite_system('sampleModel53/cfblk49','user1');
hilite_system('sampleModel53/cfblk5','user1');
hilite_system('sampleModel53/cfblk50','user1');
hilite_system('sampleModel53/cfblk51','user1');
hilite_system('sampleModel53/cfblk52','user1');
hilite_system('sampleModel53/cfblk53','user1');
hilite_system('sampleModel53/cfblk54','user1');
hilite_system('sampleModel53/cfblk55','user1');
hilite_system('sampleModel53/cfblk56','user1');
hilite_system('sampleModel53/cfblk57','user1');
hilite_system('sampleModel53/cfblk58','user1');
hilite_system('sampleModel53/cfblk6','user1');
hilite_system('sampleModel53/cfblk60','user1');
hilite_system('sampleModel53/cfblk61','user1');
hilite_system('sampleModel53/cfblk62','user1');
hilite_system('sampleModel53/cfblk63','user1');
hilite_system('sampleModel53/cfblk64','user1');
hilite_system('sampleModel53/cfblk65','user1');
hilite_system('sampleModel53/cfblk66','user1');
hilite_system('sampleModel53/cfblk67','user1');
hilite_system('sampleModel53/cfblk68','user1');
hilite_system('sampleModel53/cfblk69','user1');
hilite_system('sampleModel53/cfblk7','user1');
hilite_system('sampleModel53/cfblk70','user1');
hilite_system('sampleModel53/cfblk71','user1');
hilite_system('sampleModel53/cfblk72','user1');
hilite_system('sampleModel53/cfblk73','user1');
hilite_system('sampleModel53/cfblk74','user1');
hilite_system('sampleModel53/cfblk75','user1');
hilite_system('sampleModel53/cfblk76','user1');
hilite_system('sampleModel53/cfblk77','user1');
hilite_system('sampleModel53/cfblk78','user1');
hilite_system('sampleModel53/cfblk79','user1');
hilite_system('sampleModel53/cfblk8','user1');
hilite_system('sampleModel53/cfblk80','user1');
hilite_system('sampleModel53/cfblk81','user1');
hilite_system('sampleModel53/cfblk82','user1');
hilite_system('sampleModel53/cfblk83','user1');
hilite_system('sampleModel53/cfblk84','user1');
hilite_system('sampleModel53/cfblk85','user1');
hilite_system('sampleModel53/cfblk86','user1');
hilite_system('sampleModel53/cfblk87','user1');
hilite_system('sampleModel53/cfblk88','user1');
hilite_system('sampleModel53/cfblk89','user1');
hilite_system('sampleModel53/cfblk9','user1');
hilite_system('sampleModel53/cfblk90','user1');
hilite_system('sampleModel53/cfblk91','user1');
hilite_system('sampleModel53/cfblk92','user1');
hilite_system('sampleModel53/cfblk93','user1');
hilite_system('sampleModel53/cfblk94','user1');
hilite_system('sampleModel53/cfblk95','user1');
hilite_system('sampleModel53/cfblk96','user1');
hilite_system('sampleModel53/cfblk97','user1');
hilite_system('sampleModel53/cfblk98','user1');
hilite_system('sampleModel53/cfblk99','user1');
hilite_system('sampleModel53/cfblk50/FixPt Constant','user1');
hilite_system('sampleModel53/cfblk50/FixPt Data Type Duplicate','user1');
hilite_system('sampleModel53/cfblk50/FixPt Sum1','user1');
hilite_system('sampleModel53/cfblk47/FixPt Constant','user1');
hilite_system('sampleModel53/cfblk47/FixPt Data Type Duplicate','user1');
hilite_system('sampleModel53/cfblk47/FixPt Sum1','user1');
hilite_system('sampleModel53/cfblk4/Delay Input1','user1');
hilite_system('sampleModel53/cfblk4/FixPt Relational Operator','user1');
hilite_system('sampleModel53/cfblk4/Nonpositive','user1');
hilite_system('sampleModel53/cfblk3/Delay Input1','user1');
hilite_system('sampleModel53/cfblk3/FixPt Relational Operator','user1');
hilite_system('sampleModel53/cfblk3/Nonpositive','user1');
hilite_system('sampleModel53/cfblk29/FixPt Constant','user1');
hilite_system('sampleModel53/cfblk29/FixPt Data Type Duplicate','user1');
hilite_system('sampleModel53/cfblk29/FixPt Sum1','user1');
hilite_system('sampleModel53/cfblk23/FixPt Constant','user1');
hilite_system('sampleModel53/cfblk23/FixPt Data Type Duplicate','user1');
hilite_system('sampleModel53/cfblk23/FixPt Sum1','user1');
hilite_system('sampleModel53/cfblk14/FixPt Constant','user1');
hilite_system('sampleModel53/cfblk14/FixPt Data Type Duplicate','user1');
hilite_system('sampleModel53/cfblk14/FixPt Sum1','user1');
hilite_system('sampleModel53/cfblk1/Delay Input1','user1');
hilite_system('sampleModel53/cfblk1/FixPt Relational Operator','user1');
hilite_system('sampleModel53/cfblk3/Nonpositive/Compare','user1');
hilite_system('sampleModel53/cfblk3/Nonpositive/Constant','user1');
hilite_system('sampleModel53/cfblk4/Nonpositive/Compare','user1');
hilite_system('sampleModel53/cfblk4/Nonpositive/Constant','user1');
