-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\sampleModel53\sampleModel53.vhd
-- Created: 2024-04-27 17:04:27
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1
-- Target subsystem base rate: 1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: sampleModel53
-- Source Path: sampleModel53
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY sampleModel53 IS
END sampleModel53;


ARCHITECTURE rtl OF sampleModel53 IS

BEGIN
  -- All logic inside the DUT 'sampleModel53' was detected to be redundant by HDL Coder. Consider connecting output 
  -- ports to the design in order to preserve logic for code generation

END rtl;

