cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel41/cfblk1','user1');
hilite_system('sampleModel41/cfblk10','user1');
hilite_system('sampleModel41/cfblk100','user1');
hilite_system('sampleModel41/cfblk101','user1');
hilite_system('sampleModel41/cfblk102','user1');
hilite_system('sampleModel41/cfblk103','user1');
hilite_system('sampleModel41/cfblk104','user1');
hilite_system('sampleModel41/cfblk105','user1');
hilite_system('sampleModel41/cfblk106','user1');
hilite_system('sampleModel41/cfblk107','user1');
hilite_system('sampleModel41/cfblk108','user1');
hilite_system('sampleModel41/cfblk109','user1');
hilite_system('sampleModel41/cfblk11','user1');
hilite_system('sampleModel41/cfblk110','user1');
hilite_system('sampleModel41/cfblk111','user1');
hilite_system('sampleModel41/cfblk12','user1');
hilite_system('sampleModel41/cfblk13','user1');
hilite_system('sampleModel41/cfblk14','user1');
hilite_system('sampleModel41/cfblk15','user1');
hilite_system('sampleModel41/cfblk16','user1');
hilite_system('sampleModel41/cfblk17','user1');
hilite_system('sampleModel41/cfblk18','user1');
hilite_system('sampleModel41/cfblk19','user1');
hilite_system('sampleModel41/cfblk2','user1');
hilite_system('sampleModel41/cfblk20','user1');
hilite_system('sampleModel41/cfblk21','user1');
hilite_system('sampleModel41/cfblk22','user1');
hilite_system('sampleModel41/cfblk23','user1');
hilite_system('sampleModel41/cfblk24','user1');
hilite_system('sampleModel41/cfblk25','user1');
hilite_system('sampleModel41/cfblk26','user1');
hilite_system('sampleModel41/cfblk27','user1');
hilite_system('sampleModel41/cfblk28','user1');
hilite_system('sampleModel41/cfblk29','user1');
hilite_system('sampleModel41/cfblk3','user1');
hilite_system('sampleModel41/cfblk30','user1');
hilite_system('sampleModel41/cfblk31','user1');
hilite_system('sampleModel41/cfblk32','user1');
hilite_system('sampleModel41/cfblk33','user1');
hilite_system('sampleModel41/cfblk34','user1');
hilite_system('sampleModel41/cfblk35','user1');
hilite_system('sampleModel41/cfblk36','user1');
hilite_system('sampleModel41/cfblk37','user1');
hilite_system('sampleModel41/cfblk38','user1');
hilite_system('sampleModel41/cfblk39','user1');
hilite_system('sampleModel41/cfblk4','user1');
hilite_system('sampleModel41/cfblk40','user1');
hilite_system('sampleModel41/cfblk41','user1');
hilite_system('sampleModel41/cfblk42','user1');
hilite_system('sampleModel41/cfblk43','user1');
hilite_system('sampleModel41/cfblk44','user1');
hilite_system('sampleModel41/cfblk45','user1');
hilite_system('sampleModel41/cfblk46','user1');
hilite_system('sampleModel41/cfblk47','user1');
hilite_system('sampleModel41/cfblk48','user1');
hilite_system('sampleModel41/cfblk49','user1');
hilite_system('sampleModel41/cfblk5','user1');
hilite_system('sampleModel41/cfblk50','user1');
hilite_system('sampleModel41/cfblk51','user1');
hilite_system('sampleModel41/cfblk52','user1');
hilite_system('sampleModel41/cfblk53','user1');
hilite_system('sampleModel41/cfblk54','user1');
hilite_system('sampleModel41/cfblk55','user1');
hilite_system('sampleModel41/cfblk56','user1');
hilite_system('sampleModel41/cfblk57','user1');
hilite_system('sampleModel41/cfblk58','user1');
hilite_system('sampleModel41/cfblk59','user1');
hilite_system('sampleModel41/cfblk6','user1');
hilite_system('sampleModel41/cfblk60','user1');
hilite_system('sampleModel41/cfblk61','user1');
hilite_system('sampleModel41/cfblk62','user1');
hilite_system('sampleModel41/cfblk63','user1');
hilite_system('sampleModel41/cfblk64','user1');
hilite_system('sampleModel41/cfblk65','user1');
hilite_system('sampleModel41/cfblk66','user1');
hilite_system('sampleModel41/cfblk67','user1');
hilite_system('sampleModel41/cfblk68','user1');
hilite_system('sampleModel41/cfblk69','user1');
hilite_system('sampleModel41/cfblk7','user1');
hilite_system('sampleModel41/cfblk70','user1');
hilite_system('sampleModel41/cfblk71','user1');
hilite_system('sampleModel41/cfblk72','user1');
hilite_system('sampleModel41/cfblk73','user1');
hilite_system('sampleModel41/cfblk74','user1');
hilite_system('sampleModel41/cfblk75','user1');
hilite_system('sampleModel41/cfblk76','user1');
hilite_system('sampleModel41/cfblk8','user1');
hilite_system('sampleModel41/cfblk82','user1');
hilite_system('sampleModel41/cfblk83','user1');
hilite_system('sampleModel41/cfblk84','user1');
hilite_system('sampleModel41/cfblk85','user1');
hilite_system('sampleModel41/cfblk86','user1');
hilite_system('sampleModel41/cfblk87','user1');
hilite_system('sampleModel41/cfblk88','user1');
hilite_system('sampleModel41/cfblk89','user1');
hilite_system('sampleModel41/cfblk9','user1');
hilite_system('sampleModel41/cfblk90','user1');
hilite_system('sampleModel41/cfblk91','user1');
hilite_system('sampleModel41/cfblk92','user1');
hilite_system('sampleModel41/cfblk93','user1');
hilite_system('sampleModel41/cfblk94','user1');
hilite_system('sampleModel41/cfblk95','user1');
hilite_system('sampleModel41/cfblk96','user1');
hilite_system('sampleModel41/cfblk97','user1');
hilite_system('sampleModel41/cfblk98','user1');
hilite_system('sampleModel41/cfblk99','user1');
hilite_system('sampleModel41/cfblk62/FixPt Constant','user1');
hilite_system('sampleModel41/cfblk62/FixPt Data Type Duplicate','user1');
hilite_system('sampleModel41/cfblk62/FixPt Sum1','user1');
hilite_system('sampleModel41/cfblk5/Delay Input1','user1');
hilite_system('sampleModel41/cfblk5/FixPt Relational Operator','user1');
hilite_system('sampleModel41/cfblk5/Positive','user1');
hilite_system('sampleModel41/cfblk40/FixPt Constant','user1');
hilite_system('sampleModel41/cfblk40/FixPt Data Type Duplicate','user1');
hilite_system('sampleModel41/cfblk40/FixPt Sum1','user1');
hilite_system('sampleModel41/cfblk4/Delay Input1','user1');
hilite_system('sampleModel41/cfblk4/FixPt Relational Operator','user1');
hilite_system('sampleModel41/cfblk4/Negative','user1');
hilite_system('sampleModel41/cfblk34/FixPt Constant','user1');
hilite_system('sampleModel41/cfblk34/FixPt Data Type Duplicate','user1');
hilite_system('sampleModel41/cfblk34/FixPt Sum1','user1');
hilite_system('sampleModel41/cfblk3/Delay Input1','user1');
hilite_system('sampleModel41/cfblk3/FixPt Relational Operator','user1');
hilite_system('sampleModel41/cfblk28/FixPt Constant','user1');
hilite_system('sampleModel41/cfblk28/FixPt Data Type Duplicate','user1');
hilite_system('sampleModel41/cfblk28/FixPt Sum1','user1');
hilite_system('sampleModel41/cfblk11/AND','user1');
hilite_system('sampleModel41/cfblk11/FixPt Data Type Duplicate','user1');
hilite_system('sampleModel41/cfblk11/Lower Limit','user1');
hilite_system('sampleModel41/cfblk11/Lower Test','user1');
hilite_system('sampleModel41/cfblk11/Upper Limit','user1');
hilite_system('sampleModel41/cfblk11/Upper Test','user1');
hilite_system('sampleModel41/cfblk1/Delay Input1','user1');
hilite_system('sampleModel41/cfblk1/FixPt Relational Operator','user1');
hilite_system('sampleModel41/cfblk1/Nonpositive','user1');
hilite_system('sampleModel41/cfblk1/Nonpositive/Compare','user1');
hilite_system('sampleModel41/cfblk1/Nonpositive/Constant','user1');
hilite_system('sampleModel41/cfblk4/Negative/Compare','user1');
hilite_system('sampleModel41/cfblk4/Negative/Constant','user1');
hilite_system('sampleModel41/cfblk5/Positive/Compare','user1');
hilite_system('sampleModel41/cfblk5/Positive/Constant','user1');
