-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\sampleModel41\sampleModel41.vhd
-- Created: 2024-04-27 17:02:48
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1
-- Target subsystem base rate: 1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: sampleModel41
-- Source Path: sampleModel41
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY sampleModel41 IS
END sampleModel41;


ARCHITECTURE rtl OF sampleModel41 IS

BEGIN
  -- All logic inside the DUT 'sampleModel41' was detected to be redundant by HDL Coder. Consider connecting output 
  -- ports to the design in order to preserve logic for code generation

END rtl;

